project:
  type: book

book:
  title: "Minimal example"
  chapters:
    - index.qmd
    - My Doc.qmd


format:
  #html:
  #  theme: cosmo
  pdf:
    documentclass: book
    margin-left: 30mm
    margin-right: 30mm
    margin-top: 30mm
    margin-bottom: 30mm
    fig-pos: "hbtp"
    
    

     



